### ISSUE TITLE
Does clang need to be built in a special way?

### ISSUE THREAD

**Issue by datalogics-robb** [mgehre/xunused#1]
I downloaded the clang-8.0.0 binary distribution for Mac OS X and attempted to build, but it seems to complain about missing typeinfo in llvm:

/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/xunused.dir/link.txt --verbose=1
/Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/bin/clang++   -std=c++17 -isysroot /Applications/Xcode_10.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/xunused.dir/main.cpp.o  -o xunused  -L/Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib -Wl,-rpath,/Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib -lclangIndex -lclangTooling -lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangASTMatchers -lclangAST -lclangEdit -lclangLex -lclangBasic /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMX86AsmParser.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMSupport.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMOption.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMProfileData.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMX86Desc.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMX86AsmPrinter.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMX86Utils.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMMCDisassembler.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMObject.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMMCParser.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMMC.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMDebugInfoCodeView.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMDebugInfoMSF.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMBitReader.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMX86Info.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMCore.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMBinaryFormat.a /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMSupport.a -lz -lcurses -lm /Users/robb/clang+llvm-8.0.0-x86_64-apple-darwin/lib/libLLVMDemangle.a 
Undefined symbols for architecture x86_64:
  "typeinfo for llvm::ErrorInfoBase", referenced from:
      typeinfo for llvm::ErrorInfo<llvm::ErrorList, llvm::ErrorInfoBase> in main.cpp.o
  "typeinfo for clang::ASTConsumer", referenced from:
      typeinfo for XUnusedASTConsumer in main.cpp.o
  "typeinfo for clang::ast_matchers::MatchFinder::MatchCallback", referenced from:
      typeinfo for FunctionDeclMatchHandler in main.cpp.o
  "typeinfo for clang::ASTFrontendAction", referenced from:
      typeinfo for XUnusedFrontendAction in main.cpp.o
  "typeinfo for clang::tooling::FrontendActionFactory", referenced from:
      typeinfo for XUnusedFrontendActionFactory in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
gnumake[2]: *** [xunused] Error 1
gnumake[1]: *** [CMakeFiles/xunused.dir/all] Error 2
gnumake: *** [all] Error 2
robb@Robs-MacBook-Pro:~/SkunkWorks/xunused/build (master)$ 

Do I need to build llvm from scratch with rtti turned on?

**Comment by mgehre** [comment]
I never used the binary distribution of clang on MacOS. You might try to pass `-DLLVM_ENABLE_RTTI=ON` (or OFF?) to cmake of xunused to see if a matching combination will work.
Alternatively, you might add `-fno-rtti` into the `CMAKE_CXX_FLAGS` in CMakeLists.txt of xunused.
Please let me know how that went!

**Comment by bernhardmgruber** [comment]
I just built xunused on CentOS7 and had exactly the same issue. Passing `-DLLVM_ENABLE_RTTI=OFF` did not solve the issue, but adding `-fno-rtti` to `CMAKE_CXX_FLAGS` did it!

**Comment by mgehre** [comment]
Please try again after we updated to LLVM 10. Reopen if the issue is still there
