### ISSUE TITLE
Fails loading database

### ISSUE THREAD

**Issue by jwuttke** [mgehre/xunused#12]
First attempt to use xunused, following the instructions in `READ.me`, fails:
```
$ bear --output /io/h.json -- ninja
$ /Gext/xunused/build/xunused /io/h.json 
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "/io/h.json"
No compilation database found in /io or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
```

**Comment by mgehre** [comment]
I don't know `bear`. You need to generate a compile_commands.json from your build system, and then invoke `xunused /path/to/your/project/compile_commands.json`

**Comment by jwuttke** [comment]
https://github.com/rizsotto/Bear. Recommended at https://clang.llvm.org/docs/JSONCompilationDatabase.html.

How else generate compile_commands.json from a complex project's CMake sources?

**Comment by mgehre** [comment]
Hi, I usually let cmake generate it by setting https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html

**Comment by jwuttke** [comment]
Thank you. Works.
