### ISSUE TITLE
Support for Weak functions

### ISSUE THREAD

**Issue by dfarley1** [mgehre/xunused#7]
Thanks for making this tool, it's been really helpful finding some dead code for us!

We have a lot of `__attribute__((weak))` functions for test tracing and whatnot, is it possible to recognize these cases? I'm suspecting not since weak overrides happen during linkage but I'm not familiar enough with Clang's tooling to understand if it can figure that out.

Example that xunused thought was unused:
```
// main.c
void __attribute__((weak)) foo(void) {
}

int main(void) {
    foo();
}


// test_wrap.c

// This one was found to be "unused"
void foo(void) {
    // Does actual stuff
}
```

**Comment by dfarley1** [comment]
I found another interesting case. We have a common lib that declares a function `__attribute__((weak)) foo()` which gets overridden by two processes (C-style virtual functions are great huh??). Anyways, xunused detects only one of the overrides as unused. In both cases the overrides share the same base file name, I'm wondering if that's confusing things?

```
/*  /depot/lib/blah.c  */
void __attribute__((weak)) foo() { /* noop */ }
void bar() { foo(); }


/*  /depot/procA/qwer.c. */
void foo() { ... }        /*  This one claims to be unused!  */
void qwer() { bar(); }


/*  /depot/procB/qwer.c. */
void foo() { ... }        /*  This one does not  */
void qwer() { bar(); }
```

**Comment by mgehre** [comment]
Hey Daniel, I'm happy to hear that you found xunused useful! I'll look into the weak functions. It's likely a small fix.

**Comment by dfarley1** [comment]
Not sure if this belong in its own issue but it's another attribute that xunused doesn't appear to handle.

We use `__attribute__((constructor))` ([docs](https://gcc.gnu.org/onlinedocs/gcc-4.7.0/gcc/Function-Attributes.html)) to set up our memory allocator before `main()` runs and xunused claims this is unused:
```
# main.c

static void allocator_init(void) __attribute__((constructor(101)));
static void
allocator_init(void)
{
    // Stuff
}
```

**Comment by ghost** [comment]
I pushed a fix for both `weak` and `constructor`. Could you please check whether that covers all your use cases?

**Comment by dfarley1** [comment]
Those changes seem to have worked! Thanks so much!
